### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by runic-tears** [vimestats/front-rewrite#1]
- [x] Сделать обработку введённых данных
- [x] Выводить полученные данные от API
- [x] Настроить SEO (OGP + Meta)
